import 'dart:io';
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:ghanaclass_school_management/core/database/app_database.dart';
import 'package:intl/intl.dart';

class StudentPdfService {
  Future<Uint8List> buildProfilePdf(
    Student student,
    HealthRecord? health,
    List<AcademicHistoryData> history, {
    InstitutionalIdentityData? schoolInfo,
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    final doc = pw.Document();

    final fontBold = await PdfGoogleFonts.openSansBold();

    final schoolName = (schoolInfo?.schoolName.trim().isNotEmpty == true)
        ? schoolInfo!.schoolName.trim()
      : 'GhanaClass SMS';

    pw.ImageProvider? schoolLogo;
    final logoBytes = schoolInfo?.logoBytes;
    if (logoBytes != null && logoBytes.isNotEmpty) {
      schoolLogo = pw.MemoryImage(logoBytes);
    } else {
      final path = schoolInfo?.logoPath;
      if (path != null && path.trim().isNotEmpty) {
        try {
          final fileBytes = await File(path).readAsBytes();
          if (fileBytes.isNotEmpty) {
            schoolLogo = pw.MemoryImage(fileBytes);
          }
        } catch (_) {
          // Ignore logo read failures; PDF should still generate.
        }
      }
    }

    doc.addPage(
      pw.Page(
        pageFormat: pageFormat,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader(
                schoolName: schoolName,
                student: student,
                fontBold: fontBold,
                schoolLogo: schoolLogo,
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 20),
              _buildSectionTitle('Personal Information', fontBold),
              _buildSimpleGrid([
                {'Label': 'Full Name', 'Value': '${student.firstName} ${student.lastName} ${student.otherNames ?? ""}'},
                {'Label': 'Gender', 'Value': student.gender.toUpperCase()},
                {'Label': 'Date of Birth', 'Value': DateFormat('dd MMM yyyy').format(student.dateOfBirth)},
                {'Label': 'Student ID', 'Value': student.studentId},
                {'Label': 'Admission No', 'Value': student.admissionNumber},
              ], fontBold),
              pw.SizedBox(height: 20),
              _buildSectionTitle('Guardian Information', fontBold),
              _buildSimpleGrid([
                {'Label': 'Guardian Name', 'Value': student.guardianName},
                {'Label': 'Phone', 'Value': student.guardianPhone},
                {'Label': 'Relationship', 'Value': student.guardianRelationship},
                {'Label': 'Address', 'Value': student.guardianAddress ?? 'N/A'},
              ], fontBold),
              pw.SizedBox(height: 20),
              _buildSectionTitle('Health Record', fontBold),
              if (health != null)
                _buildSimpleGrid([
                  {'Label': 'Blood Group', 'Value': health.bloodGroup ?? 'N/A'},
                  {'Label': 'Allergies', 'Value': health.allergies ?? 'N/A'},
                  {'Label': 'Medications', 'Value': health.medications ?? 'N/A'},
                ], fontBold)
              else
                pw.Text('No health records found.'),
              pw.Stack(
                alignment: pw.Alignment.bottomRight,
                children: [
                  pw.SizedBox(height: 100),
                  pw.Text('Generated by $schoolName', style: const pw.TextStyle(color: PdfColors.grey)),
                ],
              )
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  Future<void> generateAndPrintProfile(
    Student student,
    HealthRecord? health,
    List<AcademicHistoryData> history,
    {
      InstitutionalIdentityData? schoolInfo,
    }
  ) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => buildProfilePdf(
        student,
        health,
        history,
        schoolInfo: schoolInfo,
        pageFormat: format,
      ),
    );
  }

  Future<void> generateStudentIdCard(Student student, {InstitutionalIdentityData? schoolInfo}) async {
    final doc = pw.Document();
    
    // Credit card size: 85.60 × 53.98 mm
    const cardFormat = PdfPageFormat(85.6 * PdfPageFormat.mm, 53.98 * PdfPageFormat.mm);
    final fontBold = await PdfGoogleFonts.openSansBold();

    final schoolName = (schoolInfo?.schoolName.trim().isNotEmpty == true)
      ? schoolInfo!.schoolName.trim()
      : 'School';

    doc.addPage(
      pw.Page(
        pageFormat: cardFormat,
        margin: const pw.EdgeInsets.all(0),
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.blue900, width: 2),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              children: [
                // Photo Area
                pw.Container(
                  width: 60,
                  height: 80,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey200,
                    borderRadius: pw.BorderRadius.circular(4),
                    border: pw.Border.all(color: PdfColors.grey400),
                  ),
                   child: pw.Center(child: pw.Text('PHOTO', style: const pw.TextStyle(fontSize: 8))),
                ),
                pw.SizedBox(width: 10),
                // Details
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    mainAxisAlignment: pw.MainAxisAlignment.center,
                    children: [
                      pw.Text(
                        schoolName.toUpperCase(),
                        style: pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.blue800),
                      ),
                      pw.Divider(thickness: 1, height: 4),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        '${student.firstName} ${student.lastName}',
                        style: pw.TextStyle(font: fontBold, fontSize: 12),
                      ),
                       pw.Text(
                        'ID: ${student.studentId}',
                        style: const pw.TextStyle(fontSize: 9),
                      ),
                      pw.Text(
                        'Class: JHS 1', // Placeholder
                        style: const pw.TextStyle(fontSize: 9),
                      ),
                      pw.Spacer(),
                       pw.BarcodeWidget(
                        data: student.studentId,
                        barcode: pw.Barcode.code128(),
                        height: 20,
                        width: 100,
                        drawText: false,
                      ),
                    ],
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => doc.save(),
    );
  }

  pw.Widget _buildHeader({
    required String schoolName,
    required Student student,
    required pw.Font fontBold,
    pw.ImageProvider? schoolLogo,
  }) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              schoolName,
              style: pw.TextStyle(font: fontBold, fontSize: 18, color: PdfColors.blue800),
            ),
            pw.SizedBox(height: 2),
            pw.Text(
              'STUDENT PROFILE · Academic Year ${DateTime.now().year}',
              style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
            ),
          ],
        ),
        pw.Container(
          height: 60,
          width: 60,
          decoration: const pw.BoxDecoration(
            color: PdfColors.grey200,
            shape: pw.BoxShape.circle,
          ),
          child: schoolLogo != null
              ? pw.ClipOval(child: pw.Image(schoolLogo, fit: pw.BoxFit.cover))
              : pw.Center(child: pw.Text('${student.firstName[0]}${student.lastName[0]}')),
        ),
      ],
    );
  }

  pw.Widget _buildSectionTitle(String title, pw.Font fontBold) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Text(
        title,
        style: pw.TextStyle(font: fontBold, fontSize: 16, color: PdfColors.blue600),
      ),
    );
  }

  pw.Widget _buildSimpleGrid(List<Map<String, String>> items, pw.Font fontBold) {
    return pw.Wrap(
      spacing: 20,
      runSpacing: 10,
      children: items.map((item) {
        return pw.SizedBox(
          width: 200, // Fixed width for 2-column look on A4
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(item['Label']!, style: const pw.TextStyle(color: PdfColors.grey600, fontSize: 10)),
              pw.Text(item['Value']!, style: pw.TextStyle(font: fontBold, fontSize: 12)),
            ],
          ),
        );
      }).toList(),
    );
  }
}
